const Product = [
    {
      id: 1,
      image: 'product.jpg',
      name: 'Soap Bar - Lavender Scented',
      detail: 'A relaxing lavender-scented soap bar for a soothing bath experience.',
      currentPrice: 4.99,
      prevPrice: 6.99,
      shopName: 'Soap Emporium',
      sale: true,
      rating: 4.7,
    },
    {
      id: 2,
      image: 'product.jpg',
      name: 'Hoodie - Classic Black',
      detail: 'A comfortable and stylish black hoodie for all occasions.',
      currentPrice: 29.99,
      prevPrice: 39.99,
      shopName: 'Fashion Hub',
      sale: true,
      rating: 4.5,
    },
    {
      id: 3,
      image: 'product.jpg',
      name: 'Organic Soap - Citrus Burst',
      detail: 'An organic, invigorating soap with a burst of citrus fragrance.',
      currentPrice: 6.49,
      prevPrice: 0,
      shopName: 'Green Living Store',
      sale: false,
      rating: 4.8,
    },
    {
      id: 4,
      image: 'product.jpg',
      name: 'Hoodie - Vintage Red',
      detail: 'A vintage-style red hoodie with a worn-in look and feel.',
      currentPrice: 34.99,
      prevPrice: 0,
      shopName: 'Retro Fashion Co.',
      sale: false,
      rating: 4.3,
    },
    {
      id: 5,
      image: 'product.jpg',
      name: 'Artisan Soap - Rose Petal Delight',
      detail: 'Handcrafted soap with real rose petals for a luxurious bathing experience.',
      currentPrice: 8.99,
      prevPrice: 11.99,
      shopName: 'Artisan Soaps & More',
      sale: true,
      rating: 4.9,
    },
    {
      id: 6,
      image: 'product.jpg',
      name: 'Hoodie - Cozy Gray',
      detail: 'A cozy and warm gray hoodie for chilly days and nights.',
      currentPrice: 28.99,
      prevPrice: 32.99,
      shopName: 'WinterWear Boutique',
      sale: true,
      rating: 4.6,
    },
    {
      id: 7,
      image: 'product.jpg',
      name: 'Luxury Soap Set - Exotic Scents',
      detail: 'A set of exotic scented luxury soaps for a spa-like experience at home.',
      currentPrice: 24.99,
      prevPrice: 29.99,
      shopName: 'Luxury Bath Haven',
      sale: true,
      rating: 4.7,
    },
    {
      id: 8,
      image: 'product.jpg',
      name: 'Hoodie - Sporty Blue',
      detail: 'A sporty blue hoodie for the active and adventurous individuals.',
      currentPrice: 27.99,
      prevPrice: 0,
      shopName: 'ActiveGear Outfitters',
      sale: false,
      rating: 4.4,
    },
    {
      id: 9,
      image: 'product.jpg',
      name: 'Natural Soap - Oatmeal & Honey',
      detail: 'A natural soap bar enriched with oatmeal and honey for gentle exfoliation.',
      currentPrice: 5.99,
      prevPrice: 0,
      shopName: 'Natural Wellness Co.',
      sale: false,
      rating: 4.5,
    },
    {
      id: 10,
      image: 'product.jpg',
      name: 'Hoodie - Urban Camo',
      detail: 'An urban camo-patterned hoodie for the streetwear enthusiasts.',
      currentPrice: 31.99,
      prevPrice: 0,
      shopName: 'StreetStyle Emporium',
      sale: false,
      rating: 4.6,
    },
    {
      id: 11,
      image: 'product.jpg',
      name: 'Handmade Soap - Lavender Fields',
      detail: 'A handmade soap with the calming scent of lavender fields.',
      currentPrice: 7.49,
      prevPrice: 9.99,
      shopName: 'Handcrafted Treasures',
      sale: true,
      rating: 4.8,
    },
    {
      id: 12,
      image: 'product.jpg',
      name: 'Hoodie - Vintage Denim',
      detail: 'A vintage-style denim hoodie with a worn-in look and feel.',
      currentPrice: 36.99,
      prevPrice: 0,
      shopName: 'Retro Fashion Co.',
      sale: false,
      rating: 4.3,
    },
    {
      id: 13,
      image: 'product.jpg',
      name: 'Aromatherapy Soap - Eucalyptus Mint',
      detail: 'Aromatherapy soap with the refreshing scent of eucalyptus and mint.',
      currentPrice: 6.99,
      prevPrice: 0,
      shopName: 'Relax & Rejuvenate Spa',
      sale: false,
      rating: 4.6,
    },
    {
      id: 14,
      image: 'product.jpg',
      name: 'Hoodie - Earthy Brown',
      detail: 'An earthy brown hoodie for a rugged and outdoorsy look.',
      currentPrice: 30.99,
      prevPrice: 0,
      shopName: 'Adventure Gear Outfitters',
      sale: false,
      rating: 4.2,
    },
    {
      id: 15,
      image: 'product.jpg',
      name: 'Gourmet Soap - Coffee Bliss',
      detail: 'A gourmet soap infused with the rich aroma of coffee for coffee lovers.',
      currentPrice: 8.99,
      prevPrice: 10.99,
      shopName: 'Gourmet Bath Creations',
      sale: true,
      rating: 4.9,
    },

    {
      id: 15,
      image: 'product.jpg',
      name: 'Soap Candy Smeled',
      detail: 'A relaxing lavender-scented soap bar for a soothing bath experience.',
      currentPrice: 4.99,
      prevPrice: 6.99,
      shopName: 'Soap Emporium',
      sale: true,
      rating: 4.7,
    },
  ];
  
  export default Product;
  